./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
./rtv1 scenes/light.rt
