//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t verify_user_name(void);
int32_t verify_user_pass(char * str);

// --------------------- Global Variables ---------------------

bool g1 = false; // cf
int32_t g2 = 0; // esi
struct _IO_FILE * g3 = NULL; // 0x804a020
char * g4; // 0x804a040
bool g5 = false; // zf

// ------------------------ Functions -------------------------

// Address range: 0x8048464 - 0x80484a2
int32_t verify_user_name(void) {
    int32_t v1 = g2; // bp-12
    bool v2 = &v1 < (int32_t *)16; // cf
    puts("verifying username....\n");
    int32_t v3 = (int32_t)&g4; // edx
    uint32_t strncmp_rc = strncmp((char *)&g4, "dat_wil", 7);
    g5 = strncmp_rc % 2 == 0;
    g2 = v1;
    return 0x1000000 * ((((int32_t)(v2 | strncmp_rc % 2 == 0) | v3 & -256) ^ 1) - (int32_t)v2) / 0x1000000;
}

// Address range: 0x80484a3 - 0x80484cf
int32_t verify_user_pass(char * str) {
    uint32_t strncmp_rc = strncmp(str, "admin", 5);
    g5 = strncmp_rc % 2 == 0;
    return 0x1000000 * ((((int32_t)(g1 | strncmp_rc % 2 == 0) | (int32_t)str & -256) ^ 1) - (int32_t)g1) / 0x1000000;
}

// Address range: 0x80484d0 - 0x80485bf
int main(int argc, char ** argv) {
    int32_t str;
    memset((char *)&str, 0, 16);
    puts("********* ADMIN LOGIN PROMPT *********");
    printf("Enter Username: ");
    fgets((char *)&g4, 256, g3);
    g1 = false;
    if (verify_user_name() == 0) {
        // 0x8048550
        puts("Enter Password: ");
        fgets((char *)&str, 100, g3);
        if (verify_user_pass((char *)&str) != 0) {
            // 0x8048590
            // branch -> 0x8048597
        }
        // 0x8048597
        puts("nope, incorrect password...\n");
        // branch -> 0x80485af
    } else {
        // 0x804853d
        puts("nope, incorrect username...\n");
        // branch -> 0x80485af
    }
    // 0x80485af
    return 1;
}

// --------------- Dynamically Linked Functions ---------------

// char * fgets(char * restrict s, int n, FILE * restrict stream);
// int printf(const char * restrict format, ...);
// int puts(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 3
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2018-05-07 17:41:48