#!/bin/sh

stty -raw # Réutilise le mode RAW pour l'interception des signaux et autres
stty echo # Remise en place de l'echo
stty onlcr # Remise en place du retour chariot

export DYLD_FALLBACK_FRAMEWORK_PATH="libs/libsfml/SFML/extlibs/libs-osx/Frameworks"
./bin/nibbler $1 $2 $3 $4
